### ISSUE TITLE
BraTS 2013 Experiments

### ISSUE THREAD

**Issue by MSC19950601** [mahfuzmohammad/Fixed-Point-GAN#2]
Is there any plan to release the details of experiments on BraTS13 dataset? Thank you :)

**Comment by mahfuzmohammad** [comment]
The current released code has been used for the BraTS13 dataset. I will add an example for the BraTS13 dataset soon.

**Comment by MSC19950601** [comment]
Thank you very much!

**Comment by MSC19950601** [comment]
How soon will you add an example for the BraTS13 dataset soon, thank you very much!

**Comment by mahfuzmohammad** [comment]
I am preparing it. Hopefully it will be available by next Monday. Thank you for your patience.

**Comment by MSC19950601** [comment]
Thanks for your excellent work! I've learned a lot :)

**Comment by mahfuzmohammad** [comment]
The example for the BRATS dataset is available. Please check the updated REAMDE.
